apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-rhtap-devfile-multi-component-mj54
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dxdf-tenant/mc-two-scenarios/devfile-sample-python-basic-rhtap-devfile-multi-component-mj54@sha256:6b687574895ddfc5a157d44c7a71b12062849543dba1e1ab3caea03465bbeaa2
        name: my-python
        resources: {}
status: {}
